import pygame

# Generated by CodiumAI

from src.sound import Sound

# Dependencies:
# pip install pytest-mock
import pytest

class TestSound:

    #  Loading of sound files from assets directory
    def test_loading_of_sound_files(self, mocker):
        mocker.patch('pygame.mixer.Sound')
        mocker.patch('os.path.join', return_value='dummy_path')
        sound = Sound()
        assert pygame.mixer.Sound.call_count == 4

    #  Handling missing sound files in assets directory
    def test_handling_missing_sound_files(self, mocker):
        mocker.patch('pygame.mixer.Sound', side_effect=FileNotFoundError)
        with pytest.raises(FileNotFoundError):
            sound = Sound()

    #  Setting sound_on and music_on to False when they are already False
    def test_setting_sound_on_and_music_on_to_false_when_already_false(self, mocker):
        sound = Sound()
        sound.sound_on = False
        sound.music_on = False
        assert not sound.sound_on
        assert not sound.music_on
